-- Create institute_table if not exists
CREATE TABLE IF NOT EXISTS institute_table (
    id BIGSERIAL PRIMARY KEY,
    institute_name VARCHAR(255) NOT NULL,
    address TEXT,
    province VARCHAR(100),
    district VARCHAR(100),
    zone VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Insert 396 records into institute_table
INSERT INTO institute_table (institute_name, address, province, district, zone) VALUES
    ('KOTAHENA M.M.V.', 'MAHA VIDYALA MAWATHA,COLOMBO 13', 'Western', 'Colombo', 'Colombo'),
    ('ROYAL COLLEGE', 'RAJAKEEYA MAWATHA,COLOMBO-07', 'Western', 'Colombo', 'Colombo'),
    ('ANANDA COLLEGE', 'COLOMBO-10', 'Western', 'Colombo', 'Colombo'),
    ('NALANDA COLLEGE', 'COLOMBO 10.', 'Western', 'Colombo', 'Colombo'),
    ('THURSTAN COLLEGE', 'COLOMBO 07', 'Western', 'Colombo', 'Colombo'),
    ('ANANDA B.V.', 'SRI SUMANGALA NAHIMI MW.,COL-10', 'Western', 'Colombo', 'Colombo'),
    ('GOTHAMI B.V.', 'TEMPLE RD.,COL-10', 'Western', 'Colombo', 'Colombo'),
    ('D.S.SENANAYAKE COLLEGE', 'R.G.SENANAYAKE RD, COLOMBO 07.', 'Western', 'Colombo', 'Colombo'),
    ('DEVI B.V.', 'COLOMBO 08.', 'Western', 'Colombo', 'Colombo'),
    ('SIRIMAVO BANDARANAYAKE V.', 'STANMORE CRESENT,COLOMBO 07.', 'Western', 'Colombo', 'Colombo'),
    ('ISIPATHANA COLLEGE', 'COLOMBO 05.', 'Western', 'Colombo', 'Colombo'),
    ('LUMBINI V.', 'HAVELOCK TOWN,COL-05', 'Western', 'Colombo', 'Colombo'),
    ('MAHANAMA COLLEGE', 'COLOMBO 03.', 'Western', 'Colombo', 'Colombo'),
    ('ST.PAUL''S B.V.', 'LESTER JAMES PEIRIS MW.,COL-04', 'Western', 'Colombo', 'Colombo'),
    ('VISAKHA V.', 'VAJIRA RD,COLOMBO 05.', 'Western', 'Colombo', 'Colombo'),
    ('KOLONNAWA BALIKA VIDYALAYA', 'SUGUNASARA ROAD,KOLONNAWA', 'Western', 'Colombo', 'Sri Jaya'' pura'),
    ('SRI RAJASINGHE CENTRAL COLLEGE', 'KUDABUTHGAMUWA,MULLERIYAWA NEW TOWN', 'Western', 'Colombo', 'Sri Jaya'' pura'),
    ('ANANDA SASTRALAYA', 'KOTTE', 'Western', 'Colombo', 'Sri Jaya'' pura'),
    ('ANULA VIDYALAYA', 'NUGEGODA', 'Western', 'Colombo', 'Sri Jaya'' pura'),
    ('PRESIDENT''S COLLEGE', 'RAJAGIRIYA', 'Western', 'Colombo', 'Sri Jaya'' pura'),
    ('PRESBYTERIAN GIRLS SCHOOL', 'MAJOR L.V.GUNARATHNE MW, DEHIWELA', 'Western', 'Colombo', 'Piliyandala'),
    ('PRINCE OF WALES COLLEGE', 'MORATUWA', 'Western', 'Colombo', 'Piliyandala'),
    ('PRINCESS OF WALES'' COLLEGE', 'RAWATHAWATHTHA, MORATUWA', 'Western', 'Colombo', 'Piliyandala'),
    ('SCIENCE COLLEGE', 'TEMPLER MAWATTA MOUNTLAVANIYA', 'Western', 'Colombo', 'Piliyandala'),
    ('PILIYANDALA M.M.V.', 'PILIYANDALA', 'Western', 'Colombo', 'Piliyandala'),
    ('HAMEED AL HUSSEINIE COLLAGE', 'NO.45 HUSSEINIYA STREET COLOMBO-12', 'Western', 'Colombo', 'Colombo'),
    ('VIVEKANANDA V.', '57, NEW CHETTY ST, COLOMBO 13', 'Western', 'Colombo', 'Colombo'),
    ('MUSLIM LADIES COLLEGE', 'KENSINGTON GARDEN,COLOMBO 04.', 'Western', 'Colombo', 'Colombo'),
    ('HINDU COLLEGE', 'LORENCE ROAD,COLOMBO 04.', 'Western', 'Colombo', 'Colombo'),
    ('RAMANATHAN HIN.LADIES COLLEGE', 'LORENCE RD,COLOMBO 04.', 'Western', 'Colombo', 'Colombo'),
    ('SRI SUBUTHI M.M.V', 'BATTARAMULLA', 'Western', 'Colombo', 'Sri Jaya'' pura'),
    ('BOMIRIYA M.M.V.', 'KADUWELA', 'Western', 'Colombo', 'Sri Jaya'' pura'),
    ('SEETHAWAKA CENTRAL COLLAGE', 'AVISSAWELLA.', 'Western', 'Colombo', 'Homagama'),
    ('HANWELLA RAJASINGHE CENTRAL COLLEGE', 'HANWELLA', 'Western', 'Colombo', 'Homagama'),
    ('DHARMAPALA VIDYALAYA', 'PANNIPITIYA', 'Western', 'Colombo', 'Sri Jaya'' pura'),
    ('DEFENCE SERVICES COLLEGE', 'MALAY STREET,COLOMBO 02.', 'Western', 'Colombo', 'Colombo'),
    ('MAHINDA RAJAPAKSHA COLLEGE', 'PITIPANA, HOMAGAMA.', 'Western', 'Colombo', 'Homagama'),
    ('SUNEETHA V.', 'WATAREKA PADUKKA', 'Western', 'Colombo', 'Homagama'),
    ('C.M.S. SRI JAYAWARDHANAPURA VIDYALAYA', 'MISION RD, KOTTE.', 'Western', 'Colombo', 'Sri Jaya'' pura'),
    ('ST.ANTHONY M.V.', 'VINCENT JOSEPH MAWATHA,WATTALA', 'Western', 'Gampaha', 'Kelaniya'),
    ('D.S.SENANAYAKA NATIONAL SCHOOL', 'MIRIGAMA', 'Western', 'Gampaha', 'Minuwangoda'),
    ('BANDARANAYAKA M.M.V.', 'VEYANGODA', 'Western', 'Gampaha', 'Gampaha'),
    ('SRI SANGABODHI CENTRAL COLLEGE', 'NITTABUWA', 'Western', 'Gampaha', 'Gampaha'),
    ('GALAHITIYAWA M.M.V.', 'GALAHITIYAWA,GANEMULLA', 'Western', 'Gampaha', 'Gampaha'),
    ('BANDARANAYAKA M.M.V.', 'YAKKALA ROAD, GAMPAHA', 'Western', 'Gampaha', 'Gampaha'),
    ('RATHNAWALI B.V', 'COLOMBO ROAD GAMPAHA', 'Western', 'Gampaha', 'Gampaha'),
    ('HENEGAMA CENTRAL COLLEGE', 'HENEGAMA', 'Western', 'Gampaha', 'Kelaniya'),
    ('SIYANE NATIONAL SCHOOL', 'PALUGAMA,DOMPE', 'Western', 'Gampaha', 'Gampaha'),
    ('DOMPE DEVI B.M.V.', 'DOMPE', 'Western', 'Gampaha', 'Gampaha'),
    ('GURUKULA M.V.', 'KELANIYA', 'Western', 'Gampaha', 'Kelaniya'),
    ('SRI DHARMALOKA M.M.V', 'WARAGODA RD,KELANIYA', 'Western', 'Gampaha', 'Kelaniya'),
    ('VIHARAMAHADEVI B.M.V', 'KIRIBATHGODA', 'Western', 'Gampaha', 'Kelaniya'),
    ('AL MUBARAK M.M.V.', 'MALWANA', 'Western', 'Gampaha', 'Kelaniya'),
    ('NEWSTED GIRL''S COLLEGE', 'NEGOMBO', 'Western', 'Gampaha', 'Negombo'),
    ('HARISHCHANDRA M.M.V.', 'TEMPLE ROAD NEGOMBO', 'Western', 'Gampaha', 'Negombo'),
    ('SRI PANGNANANDA M.V.', 'RADDOLUWA KOTUGODA', 'Western', 'Gampaha', 'Negombo'),
    ('NALANDA BOYS'' M.M.V.', 'MINUWANGODA', 'Western', 'Gampaha', 'Minuwangoda'),
    ('SENARATH PARANAVITHA M.V.', 'UDUGAMPOLA', 'Western', 'Gampaha', 'Minuwangoda'),
    ('CHRIST KING COLLEGE', 'THUDELLA, JA-ELA', 'Western', 'Gampaha', 'Negombo'),
    ('ST. JOHN''S M.V', 'UDAHAMULLA, PANADURA', 'Western', 'Kalutara', 'Kalutara'),
    ('SRI SUMANGALA M.V', 'HORANA ROAD, PANADURA', 'Western', 'Kalutara', 'Kalutara'),
    ('SRI SUMANGALA BALIKA M.V', 'NALLURUWA, PANADURA', 'Western', 'Kalutara', 'Kalutara'),
    ('BANDARAGAMA M.M.V.', 'BANDARAGAMA', 'Western', 'Kalutara', 'Horana'),
    ('TAXILA M.M.V', 'AGURUWATOTA ROAD, HORANA', 'Western', 'Kalutara', 'Horana'),
    ('SRIPALEE M.V', 'WEWALA,HORANA', 'Western', 'Kalutara', 'Horana'),
    ('RAJAKEEYA M V', 'HORANA', 'Western', 'Kalutara', 'Horana'),
    ('BULATHSINGHALA M.M.V', 'BULATHSINGHALA', 'Western', 'Kalutara', 'Horana'),
    ('C.W.W. KANNANGARA M.M.V.', 'MATUGAMA', 'Western', 'Kalutara', 'Matugama'),
    ('ANANDA SASTRALAYA', 'MATUGAMA', 'Western', 'Kalutara', 'Matugama'),
    ('K/DODANGODA MIRISWATTA NATIONAL SCHOOL', 'DODANGOA', 'Western', 'Kalutara', 'Kalutara'),
    ('TISSA M.M.V.', 'NAGASHANDIYA, KALUTARA NORTH', 'Western', 'Kalutara', 'Kalutara'),
    ('KALUTARA BALIKA M.V.', 'OLD ROAD, KALUTARA SOUTH', 'Western', 'Kalutara', 'Kalutara'),
    ('KALUTARA M.V.', 'KALUTARA SOUTH', 'Western', 'Kalutara', 'Kalutara'),
    ('ALUTHGAMA M.V', 'ALUTHGAMA', 'Western', 'Kalutara', 'Kalutara'),
    ('BERUWALA D.S.SENANAYAKA M.M.V', 'BERUWALA', 'Western', 'Kalutara', 'Kalutara'),
    ('ALUTHGAMWEEDIYA MUSLIM B. M. V.', 'MARIKKAR STREET, DHAGA TOWN', 'Western', 'Kalutara', 'Kalutara'),
    ('AL HUMAISARA M.M.V.', 'CHINA FORT, BERUWALA', 'Western', 'Kalutara', 'Kalutara'),
    ('WADDUWA CENTRAL COLLEGE', 'WIJAYA ROAD, WADDUWA', 'Western', 'Kalutara', 'Kalutara'),
    ('DR.COLVIN R DE SILVA COLLEGE', 'ITHTHAPANA, WALALLAVITA', 'Western', 'Kaluthara', 'Mathugama'),
    ('GALAGEDARA M.M.V', 'GALAGEDARA', 'Central', 'Kandy', 'Katugastota'),
    ('SUJATHA B.V.', 'GALAGEDARA', 'Central', 'Kandy', 'Katugastota'),
    ('HATHARALIYADDHA CENTRAL COLLEGE.', 'HATHARALIYADDHA.', 'Central', 'Kandy', 'Katugastota'),
    ('POOJAPITIYA CENTRAL COLLEGE.', 'POOJAPITIYA.', 'Central', 'Kandy', 'Katugastota'),
    ('ANKUMBURA PARAKRAMA M.M.V.', 'ANKUMBURA', 'Central', 'Kandy', 'Katugastota'),
    ('ALAWATHUGODA M.M.V', 'ALAWATHUGODA.', 'Central', 'Kandy', 'Katugastota'),
    ('NUGAWELA CENTRAL COLLEGE.', 'NUGAWELA.', 'Central', 'Kandy', 'Katugastota'),
    ('RANASINGHE PREMADASA N.S.', 'HASALAKA', 'Central', 'Kandy', 'Teldeniya'),
    ('AMUPITIYA N.S.', 'UDISPATTUWA', 'Central', 'Kandy', 'Teldeniya'),
    ('TELDENIYA N.S.', 'TELDENIYA.', 'Central', 'Kandy', 'Teldeniya'),
    ('S.W.R.D.BANDARANAYAKA N.S.', 'KUNDASALE', 'Central', 'Kandy', 'Wathegama'),
    ('RAJAWELLA HINDU N.S', 'RAJAWELLA, DIGANA', 'Central', 'Kandy', 'Wathegama'),
    ('MADINA N.S.', 'MADAWALA BAZAAR', 'Central', 'Kandy', 'Wathegama'),
    ('AZHAR CENTRAL COLLEGE.', 'AKURANA.', 'Central', 'Kandy', 'Katugastota'),
    ('AL MANAR MUS.V.', 'GALHINNA.', 'Central', 'Kandy', 'Katugastota'),
    ('AKURANA ZAHIRA CENTRAL COLLEGE.', 'BULUGAHATHANNA, AKURANA.', 'Central', 'Kandy', 'Katugastota'),
    ('BOPITIYA RAJASINGHE M.V', 'POTHGODA,MARASSANA', 'Central', 'Kandy', 'Kandy'),
    ('MARASSANA M.M.V.', 'MEERUPPA, MARASSANA', 'Central', 'Kandy', 'Kandy'),
    ('DHARMARAJA COLLEGE', 'KANDY', 'Central', 'Kandy', 'Kandy'),
    ('MAHAMAYA GIRLS COLLEGE', 'KANDY', 'Central', 'Kandy', 'Kandy'),
    ('GIRL''S HIGH SCHOOL', 'KANDY', 'Central', 'Kandy', 'Kandy'),
    ('KINGSWOOD COLLEGE', 'KANDY', 'Central', 'Kandy', 'Kandy'),
    ('PUSHPADANA B.V', 'KANDY', 'Central', 'Kandy', 'Kandy'),
    ('SRI RAHULA COLLEGE', 'KATUGASTOTA', 'Central', 'Kandy', 'Kandy'),
    ('KADUGANNAWA N.S', 'KADUGANNAWA', 'Central', 'Kandy', 'Denuwara'),
    ('SRI SWARNAJOTHI N.S.', 'KIRIBATHIKUBURA', 'Central', 'Kandy', 'Denuwara'),
    ('D.B.WIJETHUNGA M.M.V', 'DASKARA, MURUTHAGAHAMULA', 'Central', 'Kandy', 'Denuwara'),
    ('WICKRAMABAHU M.M.V.', 'GAMPOLA', 'Central', 'Kandy', 'Gampola'),
    ('WIMALADHARMA N.S', 'ATABAGE GAMPOLA', 'Central', 'Kandy', 'Gampola'),
    ('SENADHIKARI NATIONAL SCHOOL', 'UDAHENTENNA', 'Central', 'Kandy', 'Gampola'),
    ('ANURUDDA KUMARA MMV', 'NAWALAPITIYA', 'Central', 'Kandy', 'Gampola'),
    ('BADI UDDIN MAHMUD GIRLS'' COLLEGE', 'KANDY', 'Central', 'Kandy', 'Kandy'),
    ('HINDU NATIONAL SCHOOL', 'NUWARA-ELIYA ROAD PUSSELLAWA', 'Central', 'Kandy', 'Gampola'),
    ('AL MANAR MUS.M.M.V', 'HANDESSA', 'Central', 'Kandy', 'Denuwara'),
    ('ZAHIRA COLLEGE', 'ZAHIRA COLLEGE GAMPOLA', 'Central', 'Kandy', 'Gampola'),
    ('RAJASINGHE M.M.V.', 'PANVILA', 'Central', 'Kandy', 'Waththegama'),
    ('RANGIRI DAMBULLA CENTRAL COLLEGE', 'NISSANNKA MAWATHA, DAMBULLA', 'Central', 'Matale', 'Galewela'),
    ('SRI NAGA NATIONAL SCHOOL', 'NAULA', 'Central', 'Matale', 'Naula'),
    ('SRI SANGAMITHTHA B.N.S.', 'HULANGAMUWA, MATALE', 'Central', 'Matale', 'Matale'),
    ('VIJAYA NATIONAL SCHOOL', 'MATALE', 'Central', 'Matale', 'Matale'),
    ('ST THOMAS COLLEGE', 'MATALE', 'Central', 'Matale', 'Matale'),
    ('CHRIST CHURCH COLLAGE', 'MATALE', 'Central', 'Matale', 'Matale'),
    ('ZAHIRA COLLEGE', 'MATALE', 'Central', 'Matale', 'Matale'),
    ('AMINA GIRLS'' COLLEGE', 'MOLANDAPITIYA ROAD, MATALE', 'Central', 'Matale', 'Matale'),
    ('PAKKIYAM N.COLLAGE', 'DHARMAPALA MAWATHA, MATALE', 'Central', 'Matale', 'Matale'),
    ('AJMEER N.S.', 'ELKADUWA ROAD , UKUWELA', 'Central', 'Matale', 'Matale'),
    ('HINDU N.S.', 'MANDANDAWALA, MATALE', 'Central', 'Matale', 'Matale'),
    ('WEERAKEPPETIPOLA NATIONAL SCHOOL', 'AKURAMBODA', 'Central', 'Matale', 'Galewela'),
    ('GAMINI N.C.', 'NUWARAELIYA', 'Central', 'Nuwara Eliya', 'Nuwara Eliya'),
    ('JAYAHELA M.M.V', 'PUNDALUOYA', 'Central', 'Nuwara Eliya', 'Kotmale'),
    ('GAMINI DISSANAYAKE M.M.V', 'NEW TOWN, KOTMALE', 'Central', 'Nuwara Eliya', 'Kotmale'),
    ('CP/W SRI SUMANGALA N.C', 'NILDANDAHINNE', 'Central', 'Nuwara Eliya', 'Walapane'),
    ('AL-MINHAJ N.S.', 'HAPUGASTALAWA', 'Central', 'Nuwara Eliya', 'Kotmale'),
    ('PORAMADULLA CENTRAL COLLEGE', 'RIKILLAGASKADA', 'Central', 'Nuwara Eliya', 'Hanguranketha'),
    ('VICTORIA NATIONAL SCHOOL', 'ADIKARIGAMA', 'Central', 'Nuwara Eliya', 'Hanguranketha'),
    ('ST.GABRIEL GIRL''S COLLEGE', 'HATTON', 'Central', 'Nuwara Eliya', 'Hatton'),
    ('REWATHA M.M.V.', 'SRI LALITHA RAJAPAKSHA MAWATHA BALAPITIYA', 'Southern', 'Galle', 'Ambalangoda'),
    ('SRI DEVANANDA COLLEGE', 'AMBALANGODA', 'Southern', 'Galle', 'Ambalangoda'),
    ('DHARMASOKA COLLEGE', 'AMBALANGODA', 'Southern', 'Galle', 'Ambalangoda'),
    ('KARANDENIY M.M.V.', 'KARANDENIYA', 'Southern', 'Galle', 'Elpitiya'),
    ('GAMINI M.M.V', 'BENTHOTA', 'Southern', 'Galle', 'Elpitiya'),
    ('ANANDA M.M.V.', 'ELPITIYA', 'Southern', 'Galle', 'Elpitiya'),
    ('NELUWA NATIONAL SCHOOL', 'NELUWA GALLE', 'Southern', 'Galle', 'Udugama'),
    ('VIDYARAJA NATIONAL SCHOOL', 'THAWALAMA', 'Southern', 'Galle', 'Udugama'),
    ('NAGODA ROYAL NATIONAL SCHOOL', 'NAGODA,GALLE', 'Southern', 'Galle', 'Udugama'),
    ('WANDURAMBA CENTRAL COLLAGE', 'WANDURAMBA', 'Southern', 'Galle', 'Galle'),
    ('CHRIST CHURCH BOYS'' COLLEGE', 'BADDEGAMA', 'Southern', 'Galle', 'Galle'),
    ('CHRIST CHURCH GIRLS'' COLLEGE', 'BADDEGAMA', 'Southern', 'Galle', 'Galle'),
    ('SRI SUMANGALA NATIONAL SCHOOL', 'NALAGASDENIYA,HIKKADUWA', 'Southern', 'Galle', 'Ambalangoda'),
    ('DEVAPATHIRAJA COLLEGE', 'RATHGAMA', 'Southern', 'Galle', 'Ambalangoda'),
    ('MAHINDA COLLEGE', 'WOODWARD MAWATHA GALLE', 'Southern', 'Galle', 'Galle'),
    ('RICHMOND COLLEGE', 'RICHMOND HILL,GALLE', 'Southern', 'Galle', 'Galle'),
    ('RIPPON GIRL''S COLLEGE', 'RICHMOND HILL GALLE', 'Southern', 'Galle', 'Galle'),
    ('SANGHAMITTA BALIKA VIDYALAYA', 'WACKWELLA ROAD GALLE', 'Southern', 'Galle', 'Galle'),
    ('SOUTHLANDS COLLEGE', 'FORT GALLE', 'Southern', 'Galle', 'Galle'),
    ('SAINT ALOSIUS COLLEGE', 'KALUWELLA,GALLE', 'Southern', 'Galle', 'Galle'),
    ('VIDYALOKA COLLEGE', 'WACKWELLA ROAD,GALLE', 'Southern', 'Galle', 'Galle'),
    ('UPANANDA NATIONAL COLLEGE', 'MANAVILA,WALAHANDUWA', 'Southern', 'Galle', 'Galle'),
    ('MEEPAWALA AMARASURIYA COLLEGE', 'MEEPAWALA PODDALA', 'Southern', 'Galle', 'Galle'),
    ('KATHALUWA M.M.V.', 'KATHALUWA,AHANGAMA', 'Southern', 'Galle', 'Galle'),
    ('BATEMULLA NATIONAL SCHOOL', 'IMADUWA, GALLE', 'Southern', 'Galle', 'Galle'),
    ('BUONAVISTA COLLEGE', 'RUMASSALA,UNAWATUNA,GALLE.', 'Southern', 'Galle', 'Galle'),
    ('ZAHIRA COLLEGE (NATIONAL SCHOOL)', 'KURUNDUWATTA,GINTOTA,GALLE', 'Southern', 'Galle', 'Galle'),
    ('MALHARUSSULHIYA CENTRAL COLLEGE', 'H.K. EDMOND MAWATHA,GALLE', 'Southern', 'Galle', 'Galle'),
    ('SIRIDAMMA COLLEGE', 'LABUDUWA,AKMEEMANA.', 'Southern', 'Galle', 'Galle'),
    ('JANADIPATHI BALIKA VIDYALAYA', 'WALAHANDUWA', 'Southern', 'Galle', 'Galle'),
    ('PUHULWALLA M.M.V.', 'KIRINDA, PUHULWALLA.', 'Southern', 'Matara', 'Mulatiyana (Hakmana)'),
    ('MORAWAKA KEERTHI ABEWICKRAMA NATIONAL SCHOOL', 'DENIYAYA ROAD ,MORAWAKA', 'Southern', 'Matara', 'Morawaka'),
    ('KOTAPOLA NATIONAL SCHOOL', 'KOTAPOLA', 'Southern', 'Matara', 'Morawaka'),
    ('MR/URUBOKKA NATTONAL SCHOOL', 'URUBOKKA NATTONAL SCHOOL-URUBOKKA', 'Southern', 'Matara', 'Morawaka'),
    ('DENIYAYA CENTRAL COLLEGE', 'MR/DENIYAYA CENTRAL COLLEGE DENIYAYA', 'Southern', 'Matara', 'Morawaka'),
    ('THELIJJAWILA M.M.V.', 'THELIJJAWILA.', 'Southern', 'Matara', 'Akuressa'),
    ('GODAPITIYA M M V', 'AKURESSA', 'Southern', 'Matara', 'Akuressa'),
    ('NARANDENIYA M.V.V.', 'KAMBURUPITIYA', 'Southern', 'Matara', 'Mulatiyana (Hakmana)'),
    ('THIHAGODA M.M.V.', 'THIHAGODA,MATARA.', 'Southern', 'Matara', 'Mulatiyana (Hakmana)'),
    ('DEIYANDARA M.M.V', 'DEIYANDARA', 'Southern', 'Matara', 'Mulatiyana (Hakmana)'),
    ('SIDDHARTHA COLLGE', 'HETTIWEEDIYA.WELIGAMA', 'Southern', 'Matara', 'Matara'),
    ('SRI SUMANGALA BALIKA VIDYALAYA', 'WELIGAMA', 'Southern', 'Matara', 'Matara'),
    ('ARAFA CENTRAL COLLEGE', 'WELIGAMA', 'Southern', 'Matara', 'Matara'),
    ('RAHULA COLLEGE', 'MATARA', 'Southern', 'Matara', 'Matara'),
    ('SUJATHA VIDYALAYA', 'RAHULA ROAD MATHARA', 'Southern', 'Matara', 'Matara'),
    ('MATARA CENTRAL COLLEGE', 'RAHULA  ROAD  MATARA', 'Southern', 'Matara', 'Matara'),
    ('ST.THOMAS COLLEGE', 'KUMARATHUNGE MAWATHA,MATARA.', 'Southern', 'Matara', 'Matara'),
    ('ST THOMAS GIRLS SCHOOL', 'WALPOLA MATARA', 'Southern', 'Matara', 'Matara'),
    ('ST SERVATIUS COLLAGE', 'KOTUWEGODA MATARA', 'Southern', 'Matara', 'Matara'),
    ('DEVINUWERA CENTRAL COLLEGE', 'DEVINUWERA', 'Southern', 'Matara', 'Matara'),
    ('VIJITHA CENTRAL  COLLEGE', 'DICKWELLA', 'Southern', 'Matara', 'Matara'),
    ('MR/MINHATH NATIONAL SHOOL', 'SANDIS, ROAD, DICKWELLA', 'Southern', 'Matara', 'Matara'),
    ('MR/MAHINDARAJAPAKSHA COLLAGE', 'SARASAVI UYANA MATARA', 'Southern', 'Matara', 'Matara'),
    ('WALASMULLA M.V', 'WALASMULLA', 'Southern', 'Hambantota', 'Walasmulla'),
    ('H/KATUWANA M.V', 'KATUWANA', 'Southern', 'Hambantota', 'Walasmulla'),
    ('WEERAKETIYA RAJAPAKSHA CENTRAL COLLEGE', 'WEERAKETIYA', 'Southern', 'Hambantota', 'Walasmulla'),
    ('TANGALLE BOYAS M.M.V', 'TANGALLE', 'Southern', 'Hambantota', 'Tangalle'),
    ('TANGALLA B.V', 'TANGALLA', 'Southern', 'Hambantota', 'Tangalle'),
    ('VIJAYABA N.S.', 'HUNGAMA', 'Southern', 'Hambantota', 'Hambantota'),
    ('MAHANAGA N.S.', 'ANGUNUKOLAPELESSA.', 'Southern', 'Hambantota', 'Tangalle'),
    ('GATAMANNA VIJAYA M.M.V.', 'GATAMANNA', 'Southern', 'Hambantota', 'Tangalle'),
    ('DEBARAWEWA CENTRAL SCHOOL', 'DEBARAWEWA,THISSAMAHARAMA', 'Southern', 'Hambantota', 'Hambantota'),
    ('THARAPUTHTA M.M.V.', 'WADURUPPA RODE,AMBALANTOTA.', 'Southern', 'Hambantota', 'Hambantota'),
    ('ST.MARY''S COLLEGE', 'HAMBANTOTA', 'Southern', 'Hambantota', 'Hambantota'),
    ('ZAHIRA COLLEGE', 'BARRACK STREET, HAMBANTOTA', 'Southern', 'Hambantota', 'Hambantota'),
    ('SOORIYAWEWA M,M,V', 'VIDYAAL MAWATA,SOORIYAWEWA', 'Southern', 'Hambantota', 'Hambantota'),
    ('RUHUNU VIJAYABA N.S.', 'SITINAMALUWA, BELIATTA', 'Southern', 'Hambantota', 'Tangalle'),
    ('PUWAKDANDAWA DHAMMAPALA BALIKA VIDYALAYA', 'PUWAKDANDAWA, BELIATTA', 'Southern', 'Hambantota', 'Tangalle'),
    ('TZUCHI NATIONAL SCHOOL', 'SIRIBOPURA,HAMBANTOTA', 'Southern', 'Hambantota', 'Hambantota'),
    ('SRI LANKA SINGAPORE B.V.', 'KONDAGALA,WEERAKETIYA', 'Southern', 'Hambantota', 'Walasmulla'),
    ('MANIPAY HINDU COLLEGE', 'SANGARAPILLAI ROAD, MANIPAY', 'Nothern', 'Jaffna', 'Valikamam'),
    ('NELLIADY CENTRAL COLLEGE', 'KARAVEDDY', 'Nothern', 'Jaffna', 'Vadamarachchi'),
    ('CHAVAKACHCHERI HINDU COLLEGE', 'KANDY ROAD CHAVAKACHCHERI', 'Nothern', 'Jaffna', 'Thenmarachchi'),
    ('JAFFNA HINDU COLLEGE', 'K K S ROAD JAFFNA', 'Nothern', 'Jaffna', 'Jaffna'),
    ('JAFFNA CENTRAL COLLEGE', 'JAFFNA CENTRAL COLLEGE,JAFFNA', 'Nothern', 'Jaffna', 'Jaffna'),
    ('HOLY FAMILY CONVENT', 'VEMBADY ROAD, JAFFNA', 'Nothern', 'Jaffna', 'Jaffna'),
    ('VEMBADI GIRLS'' HIGH SCHOOL', '1ST CROSS STREET, JAFFNA', 'Nothern', 'Jaffna', 'Jaffna'),
    ('METHODISTHA HIGH LADIE''S SCHOOL', 'POINT PEDRO', 'Nothern', 'Jaffna', 'Wadamarachchi'),
    ('KILINOCHCHI M.M.V.', 'A9, ROAD, ANANTHAPURAM, KIINOCHCHI', 'Nothern', 'Kilinochchi', 'Kilinochchi'),
    ('MULANKAVIL M.V.', 'MULANKAVIL, POONAKARY', 'Nothern', 'Kilinochchi', 'Kilinochchi'),
    ('PALLAI M.V.', 'A9, ROAD, PALLAI.', 'Nothern', 'Kilinochchi', 'Kilinochchi'),
    ('SITHIVINAYAKAR HINDU COLLEGE', 'UPPUKKULAM MANNAR', 'Nothern', 'Mannar', 'Mannar'),
    ('ST.XAVIER''S BOYS COLLEGE', 'THALAIMANNAR ROAD,SINNAKADAI,MANNAR', 'Nothern', 'Mannar', 'Mannar'),
    ('ST.XAVIER''S GIRLS COLLEGE NS', 'MANNAR', 'Nothern', 'Mannar', 'Mannar'),
    ('AL-AZHAR.M.V', 'MANNAR', 'Nothern', 'Mannar', 'Mannar'),
    ('MUSALI NATIONAL SCHOOL', 'MUSALI CHILAWATHURAI , P.O BOX:-41004', 'Nothern', 'Mannar', 'Mannar'),
    ('VIDYANANDA COLLEGE', 'MULLIYAWALAI', 'Nothern', 'Mulaitivu', 'Mullaitivu'),
    ('MALLAVICENNTRAL COLLAGE', 'YOGAPURAM', 'Nothern', 'Mulaitivu', 'Thunukkai'),
    ('RAMBAIKULAM GIRLS MAHA VIDYALAYAM', 'RAMBAIKULAM VAVUNIYA', 'Nothern', 'Vavuniya', 'Vavuniya'),
    ('TAMIL MADYA MAHA VIDYALAYAM', 'KANDY ROAD VAVUNIYA', 'Nothern', 'Vavuniya', 'Vavuniya'),
    ('MUSLIM.M.V', 'MANNARROAD,PADDANICHOOR,VAVUNIYA', 'Nothern', 'Vavuniya', 'Vavuniya'),
    ('GAMINI NATIONAL SCHOOL', 'MANAR ROAD, VAVUNIYA', 'Nothern', 'Vavuniya', 'Vavuniya'),
    ('MADUKANDA NATIONAL SCHOOL', 'MADUKANDA VAVUNIYA', 'Nothern', 'Vavuniya', 'Vavuniya'),
    ('SAMPATHNUWARA M.V.', 'SAMPATHNUWARA, WELOOYA, ETHAWETUNUWEWA', 'Nothern', 'Mulaitivu', 'Mullaitivu'),
    ('BT/BC/ODDAMAVADI CENTRAL COLLEGE', 'MAIN STREET, ODDAMAVADI-01', 'Eastern', 'Batticaloa', 'Batticaloa Central'),
    ('BT/BC/VALAICHENAI AN-NOOR M.V(NATIOAL SCHOOL)', 'MAIN CROSS ROAD,VALAICHENAI-05', 'Eastern', 'Batticaloa', 'Batticaloa Central'),
    ('BT/KK/VALAICHENAI HINDU COLLEGE', 'VALAICHENAI', 'Eastern', 'Batticaloa', 'Kalkudah'),
    ('BT/BC/ALIGHAR CENTRAL COLLEGE', 'ERAVUR', 'Eastern', 'Batticaloa', 'Batticaloa Central'),
    ('BT/BC/MACAN MARKAR MAHA VIDYALAYA', 'ERAVUR', 'Eastern', 'Batticaloa', 'Batticaloa Central'),
    ('BT/VINCENT GIRLS'' HIGH SCHOOL', 'CHAPEL STREET, BATTICALOA', 'Eastern', 'Batticaloa', 'Batticaloa'),
    ('BT/BT/ST.MICHAELS,COLLEGE', 'NO.1 CENTRAL ROAD BATTICALOA.', 'Eastern', 'Batticaloa', 'Batticaloa'),
    ('BT/ST.CECILIA''S GIRLS'' COLLEGE', '2ND CROSS ROAD, BATTICALOA', 'Eastern', 'Batticaloa', 'Batticaloa'),
    ('BT/SHIVANANDA VIDYALAYA (NATIONAL SCHOOL)', 'KALLADY UPPODAI, BATTICALOA', 'Eastern', 'Batticaloa', 'Batticaloa'),
    ('BT/BC/KATTANKUDY CENTRAL COLLEGE', '322,BEACH ROAD,NEW KATTANKUDY', 'Eastern', 'Batticaloa', 'Batticaloa Central'),
    ('BT/BC/MEERA BALIKA MAHA VIDYALAYA', 'MAIN ROAD KATTANKUDY', 'Eastern', 'Batticaloa', 'Batticaloa Central'),
    ('BT/PD/PADDIRUPPU MADYA MAHA VIDYALAYA', 'KALUWANCHIKUDY - 30200', 'Eastern', 'Batticaloa', 'Paddrippu'),
    ('BT/PD/ KALUTHAVALAI MAHA VIDYALAYA', 'PADDIRUPPU', 'Eastern', 'Batticaloa', 'Paddrippu'),
    ('AM/MH/PADIYATHALAWA M.M.V.', 'PADIYATHALAWA', 'Eastern', 'Ampara', 'Mahaoya'),
    ('UHANA MAHA VIDYALAYA', 'UHANA.', 'Eastern', 'Ampara', 'Ampara'),
    ('D.S.SENANAYAKA M.M.V.', 'AMPARA', 'Eastern', 'Ampara', 'Ampara'),
    ('AM/BANDARANAYAKE BALIKA MAHA VIDYALAYA', 'AMPARA', 'Eastern', 'Ampara', 'Ampara'),
    ('KM/KM/AL - ASHRAQ MAHA VIDYALAYA(NATIONAL SCHOOL', 'MAIN STREET NINTHAVUR 25', 'Eastern', 'Ampara', 'Kalmunai'),
    ('DEHIATTAKANDIYA M.M.V.', 'DEHIATTAKANDIYA', 'Eastern', 'Ampara', 'Dehiattakandiya'),
    ('SAMMANTHURAI MUSLIM MADHAYA MAHA VIDYALAYAM', 'AMPARA ROAD, SAMMANTHURAI', 'Eastern', 'Ampara', 'Sammanthurai'),
    ('KM/KM/ZAHIRA COLLEGE', 'ZAHIRA COLLEGE ROAD,SAINTHAMARUTU -02', 'Eastern', 'Ampara', 'Kalmunai'),
    ('KM/KM/CARMEL FATIMA COLLEGE NATIONAL SCHOOL', 'YARD ROAD KALMUNAI', 'Eastern', 'Ampara', 'Kalmunai'),
    ('MAHMUD LADIES COLLEGE', 'KALMUNAI', 'Eastern', 'Ampara', 'Kalmunai'),
    ('AK/AKKARAIPATTU MUSLIM CENTRAL COLLEGE(N/S)', 'AKKARAIPATTU-06', 'Eastern', 'Ampara', 'Akkaraipattu'),
    ('KM/AK/ADDALAICHENAI MMV NATIONAL SCHOOL', 'MAIN STREET ADDALAICHENAI - 14', 'Eastern', 'Ampara', 'Akkaraipattu'),
    ('SRI RAMAKRISHNA COLLEGE N.S', 'AKKARAIPATTU', 'Eastern', 'Ampara', 'Thirukkovil'),
    ('THAMBILUVIL M.M.V.', 'MAIN STREET, THAMBILUVIL', 'Eastern', 'Ampara', 'Thirukkovil'),
    ('KM/AK/POTHUVIL CENTRAL COLLEGE', 'POTHUVIL', 'Eastern', 'Ampara', 'Akkaraipattu'),
    ('KM/ST/AL - MARJAN LADIES COLLEGE', 'SAMMANTHURAI', 'Eastern', 'Ampara', 'Sammanthurai'),
    ('ASHRAFF CENTRAL COLLEGE', 'IRAKKAMAM-09', 'Eastern', 'Ampara', 'Sammanthurai'),
    ('T/T/SRI SHANMUGA HINDU LADIES COLLEGE', 'VIDYALAYAM ROAD TRINCOMALEE', 'Eastern', 'Trincomalee', 'Trincomalee'),
    ('T/T/SINHALA MADYA MAHA VIDYALAYA', 'INNER HARBOUR ROAD, TRINCOMALEE', 'Eastern', 'Trincomalee', 'Trincomalee'),
    ('T/T/RAJAKEEYA VIDYALOKA MAHA VIDYALAYA(N:S)', 'NORTH COAST ROAD,TRINCOMALEE', 'Eastern', 'Trincomalee', 'Trincomalee'),
    ('T/T/ST.MARY''S COLLEGE', 'DOCKYARD ROAD, TRINCOMALEE', 'Eastern', 'Trincomalee', 'Trincomalee'),
    ('T/T/R.K.M.SRI KONESWARA HINDU COLLEGE', '246,DOCKYARD ROAD TRINCOMALEE', 'Eastern', 'Trincomalee', 'Trincomalee'),
    ('T/T/ST. JOSEPH''S COLLEGE', 'POWER HOUSE ROAD TRINCOMALEE', 'Eastern', 'Trincomalee', 'Trincomalee'),
    ('MAHADULWEWA M.V', 'MAHADULWEWA', 'Eastern', 'Trincomalee', 'Trincomalee North'),
    ('AGRABODHI NATIONAL SCHOOL', 'KANTHALE', 'Eastern', 'Trincomalee', 'Kantalai'),
    ('T/MU/CENTRAL COLLEGE', 'KNOX ROAD MUTUR', 'Eastern', 'Trincomalee', 'Mutur'),
    ('Kin/Al AUQSHA', 'KINNIYA.', 'Eastern', 'Trincomalee', 'Kinniya'),
    ('T/KIN/KINNIYA MUSLIM LADIES COLLEGE', 'KINNIYA.', 'Eastern', 'Trincomalee', 'Kinniya'),
    ('KINNIYA CENTRAL COLLEGE', 'MAIN STREET KINNIYA', 'Eastern', 'Trincomalee', 'Kinniya'),
    ('PARAKRAMABAHU M.M.V NATIONAL SCHOOL', 'POLGAHAWELA', 'North Western', 'Kurunegala', 'Kurunegala'),
    ('KU/MAWATHAGAMA CENTRAL COLLEGE', 'MAWATHAGAMA', 'North Western', 'Kurunegala', 'Kurunegala'),
    ('KU/SRI NISSHANKA M.M.V.', 'INDULGODAKANDA KURUNEGALA', 'North Western', 'Kurunegala', 'Kurunegala'),
    ('SRI SUMANGALA M.M.V.', 'WARIYAPOLA', 'North Western', 'Kurunegala', 'Nikaweratiya'),
    ('IBBAGAMUWA CENTRAL COLLEGE', 'IBBAGAMUWA', 'North Western', 'Kurunegala', 'Ibbagamuwa'),
    ('S.B.HERATH M.M.V.', 'NIKADALUPOTHA', 'North Western', 'Kurunegala', 'Ibbagamuwa'),
    ('MAYURAPADA CENTRAL COLLEGE', 'NARAMMALA', 'North Western', 'Kurunegala', 'Giriulla'),
    ('KU/MALIYADEVA BALIKA VIDYALAYA', 'COLOMBO ROAD, KURUNEGALA', 'North Western', 'Kurunegala', 'Kurunegala'),
    ('KU/MALIYADEVA COLLEGE', 'NEGOMBO ROAD, KURUNEGALA', 'North Western', 'Kurunegala', 'Kurunegala'),
    ('KU/PARAGAHADENIYA NATIONAL SCHOOL', 'PARAGAHADENIYA', 'North Western', 'Kurunegala', 'Kurunegala'),
    ('D.S.SENANAYAKA M.M.V.', 'UHUMIYA', 'North Western', 'Kurunegala', 'Kurunegala'),
    ('SRI RAHULA N.S', 'ALAWWA.', 'North Western', 'Kurunegala', 'Giriulla'),
    ('SRI SARANANKARA NATIONAL SCHOOL', 'BINGIRIYA', 'North Western', 'Kurunegala', 'Kuliyapitiya'),
    ('GIRI NAKKAWATHTHA MADYA MAHA VIDYALAYA', 'NAKKAWATHTHA NAKKAWATHTHA', 'North Western', 'Kurunegala', 'Giriulla'),
    ('J.R.JAYAWARDAANA M.M.V', 'DUMMALASOORIYA.', 'North Western', 'Kurunegala', 'Kuliyapitiya'),
    ('CENTRAL COLLEGE KULIYAPITIYA', 'MEEGAHAKOTUWA,KULIYAPITIYA', 'North Western', 'Kurunegala', 'Kuliyapitiya'),
    ('SARANATH VIDYALAYA', 'KULIYAPITIYA.', 'North Western', 'Kurunegala', 'Kuliyapitiya'),
    ('GIRI SANDALANKA CENTRAL COLLAGE', 'SANDALANKAWA', 'North Western', 'Kurunegala', 'Giriulla'),
    ('WICKRAMASHILA M M V', 'GIRIULLA', 'North Western', 'Kurunegala', 'Giriulla'),
    ('PANNALA NATIONAL SCHOOL', 'PANNALA', 'North Western', 'Kurunegala', 'Giriulla'),
    ('PANDUWASNUWARA S.W.R.D.BANDARANAYAKA M.M.V.', 'HETTIPOLA', 'North Western', 'Kurunegala', 'Kuliyapitiya'),
    ('KEKUNAGOLLA  NATIONAL SCHOOL', 'KEKUNAGOLLA', 'North Western', 'Kurunegala', 'Giriulla'),
    ('GIRI MADEENA NATIONAL SCHOOL', 'SIYSBALAGASKOTUWA', 'North Western', 'Kurunegala', 'Giriulla'),
    ('POLPITHIGAMA NATIONAL SCHOOL', 'POLPITHIGAMA', 'North Western', 'Kurunegala', 'Maho'),
    ('VIJAYABA CENTRAL COLEGE', 'MAHO', 'North Western', 'Kurunegala', 'Maho'),
    ('U B WANNINAYAKA CENTRAL COLLAGE', 'GALGAMUWA', 'North Western', 'Kurunegala', 'Maho'),
    ('PERAKUMPURA NATIONAL SCHOOL', 'R L B TRACT 03 SOLEPURA', 'North Western', 'Kurunegala', 'Maho'),
    ('MAHAWELI N.S', 'MEEGALEWA', 'North Western', 'Kurunegala', 'Maho'),
    ('MAHASEN N.S.', 'NIKAWERATIYA', 'North Western', 'Kurunegala', 'Nikaweratiya'),
    ('SRI PARACKRAMA M.M.V', 'KOBEIGANE', 'North Western', 'Kurunegala', 'Nikaweratiya'),
    ('KU/VISHVODA COLLEGE', 'BOYAGANE,KURUNEGALA.', 'North Western', 'Kurunegala', 'Kurunegala'),
    ('ANANDA NATIONAL SCHOOL', 'ANADA STREET,PUTTALAM.', 'North Western', 'Puttalam', 'Puttalam'),
    ('ZAHIRA NATIONAL COLLAGE', 'MANNAR RD,PUTTALAM.', 'North Western', 'Puttalam', 'Puttalam'),
    ('AL AQSA NATIONAL SCHOOL', 'U.M.U.ROAD, KALPITIYA', 'North Western', 'Puttalam', 'Puttalam'),
    ('ANANDA NATIONAL SCHOOL', 'COLOMBO ROAD CHILAW', 'North Western', 'Puttalam', 'Chilaw'),
    ('SENANAYAKA CENTRAL COLLEGE', 'MADAMPE', 'North Western', 'Puttalam', 'Chilaw'),
    ('ST. JOSHEP VAZ COLLEGE', 'WENNAPPUWA', 'North Western', 'Puttalam', 'Chilaw'),
    ('DHAMMISSARA  NATIONAL SCHOOL', 'NATHTHANDIYA', 'North Western', 'Puttalam', 'Chilaw'),
    ('BUDDHIST GIRLS'' COLLEGE', 'KIRIMATIYANA', 'North Western', 'Puttalam', 'Chilaw'),
    ('MAITHREEPALA SENANAYAKA M.M.V', 'MEDAWACHCHIYA', 'North Central', 'Anuradhapura', 'Kebithigollewa'),
    ('ANURADHAPURA CENTRAL COLLEGE', 'ANURADHAPURA', 'North Central', 'Anuradhapura', 'Anuradhapura'),
    ('SWARNAPALI BALIKA M.V', 'ANURADHAPURA', 'North Central', 'Anuradhapura', 'Anuradhapura'),
    ('SRI SIDDHARTHA CENTRAL COLLEGE', 'EPPAWALA', 'North Central', 'Anuradhapura', 'Tambuttegama'),
    ('TAMBUTTEGAMA M.V.', 'TAMBUTTEGAMA', 'North Central', 'Anuradhapura', 'Tambuttegama'),
    ('NCP/ANU/KK/KK/KEKIRAWA CENTRAL COLLEGE', 'KEKIRAWA', 'North Central', 'Anuradhapura', 'Kekirawa'),
    ('VIDYARTHA M.V.', 'KEKIRAWA', 'North Central', 'Anuradhapura', 'Kekirawa'),
    ('ZAHIRA M.V', 'ANURADHAPURA', 'North Central', 'Anuradhapura', 'Anuradhapura'),
    ('MINNERIYA N.S.', 'HINGURAKGODA', 'North Central', 'Polonnaruwa', 'Hingurakgoda'),
    ('ANANDA BALIKA N.S.', 'HINGURAKGODA', 'North Central', 'Polonnaruwa', 'Hingurakgoda'),
    ('MEDIRIGIRIYA N.S', 'MEDIRIGIRIYA', 'North Central', 'Polonnaruwa', 'Hingurakgoda'),
    ('DIWULANKADAWALA CENTRAL COLLEGE', 'DIWULANKADAWALA.', 'North Central', 'Polonnaruwa', 'Hingurakgoda'),
    ('ROYAL CENTRAL COLLEGE', 'NEW TOWN POLONNARUWA', 'North Central', 'Polonnaruwa', 'Polonnaruwa'),
    ('THOPAWEVA CENTRAL COLLEGE', 'POLONNARUWA.', 'North Central', 'Polonnaruwa', 'Polonnaruwa'),
    ('WILAYAYA CENTRAL COLLEGE', 'ARALAGANWILA.', 'North Central', 'Polonnaruwa', 'Dibulagala'),
    ('MUSLIM CENTRAL COLLEGE', 'KADURUWELA.', 'North Central', 'Polonnaruwa', 'Polonnaruwa'),
    ('BAKAMOONA MAHASEN MAHA VIDYALAYA .', 'Bakamoona', 'North Central', 'Polonnaruwa', 'Hingurakgoda'),
    ('ANDAULPOTHA N.S', 'URANIYA,MAHIYANGANAYA', 'Uva', 'Badulla', 'Mahiyanganaya'),
    ('MAHIYANGANA N.S', 'MAHIYANGANAYA', 'Uva', 'Badulla', 'Mahiyanganaya'),
    ('KANDEGEDRA M.M.V.', 'KANDEGEDRA, HALI-ELA', 'Uva', 'Badulla', 'Viyaluwa'),
    ('D.S.SENANAYAKA M.M.V.', 'KANDAKETIYA,BADULLA', 'Uva', 'Badulla', 'Viyaluwa'),
    ('MEEGAHAKIULA M.M.V.', 'MEEGAHAKIULA', 'Uva', 'Badulla', 'Viyaluwa'),
    ('PASSARA CENTRAL COLLAGE', 'PASSARA', 'Uva', 'Badulla', 'Passara'),
    ('B DHARMADUTHA COLLEGE', 'BADULLA', 'Uva', 'Badulla', 'Badulla'),
    ('B BADULLA M M V', 'BADULLA', 'Uva', 'Badulla', 'Badulla'),
    ('B VISHAKA GIRLS HIGH SCHOOL', 'BADULLA', 'Uva', 'Badulla', 'Badulla'),
    ('ATTAMPITIYA NATIONAL COLLEGE', 'ATTAMPITIYA', 'Uva', 'Badulla', 'Badulla'),
    ('HALIELA M M V', 'HALIELA', 'Uva', 'Badulla', 'Badulla'),
    ('BANDARAWELA M.M.V.', 'KINIGAMA,BANDARAWELA', 'Uva', 'Badulla', 'Bandarawela'),
    ('VISHAKA BALIKA MADYA MAHA VIDYALAYA', 'BANDARAWELA', 'Uva', 'Badulla', 'Bandarawela'),
    ('NAULLA M.M.V.', 'DEMODARA', 'Uva', 'Badulla', 'Bandarawela'),
    ('ST. JOSEPH''S MAHA VIDYALAYA', 'BANDARAWELA', 'Uva', 'Badulla', 'Bandarawela'),
    ('HALPE NATIONAL SCHOOL', 'HELA HALPE,BANDARAWELA', 'Uva', 'Badulla', 'Bandarawela'),
    ('B/KUDAKUSUM B.M.V.', 'BANDARAWELA', 'Uva', 'Badulla', 'Bandarawela'),
    ('SRI JANANANDA NATIONAL SCHOOL', 'KADURUGAMUWA, DIYATHALAWA', 'Uva', 'Badulla', 'Bandarawela'),
    ('ANANADA M.M.V(WALHAPUTHENNA M.M.V.)', 'WALHAPUTHENNA,HALDUMMULLA', 'Uva', 'Badulla', 'Bandarawela'),
    ('KAHAGOLLA NATIONAL SCHOOL', 'KAHAGOLLA"DIYATHALAWA', 'Uva', 'Badulla', 'Bandarawela'),
    ('KOSLANDA M.M.V.', 'WELLAWAYA ROAD, KOSLANDA.', 'Uva', 'Badulla', 'Bandarawela'),
    ('WELIMADA MADYA V.', 'WELIMADA', 'Uva', 'Badulla', 'Welimada'),
    ('WANGIYAKUMBURA M.V.', 'BORALANDA', 'Uva', 'Badulla', 'Welimada'),
    ('LUNUWATTA M.M.V.', 'LUNUWATTA', 'Uva', 'Badulla', 'Welimada'),
    ('MUSLIM CENTRAL COLLEGE', 'GURUTHALAWA', 'Uva', 'Badulla', 'Welimada'),
    ('B SARASWATHY CENTRAL COLLEGE', 'MAHIYANGANA ROAD BADULLA', 'Uva', 'Badulla', 'Badulla'),
    ('PASSARA TAMIL M.V.', 'PASSARA', 'Uva', 'Badulla', 'Passara'),
    ('WELLASSA M.M.V.', 'HEWELWELA, BIBILE', 'Uva', 'Monaragala', 'Bibile'),
    ('YASODARA N.C.', 'Bibila', 'Uva', 'Monaragala', 'Bibile'),
    ('MEDAGAMA M.M.V.', 'MEDAGAMA, BIBILE', 'Uva', 'Monaragala', 'Bibile'),
    ('MAHANAMA M.M.V.', 'MONARAGALA', 'Uva', 'Monaragala', 'Monaragala'),
    ('RAJAKEEYA VIDYALAYA', 'MONARAGALA', 'Uva', 'Monaragala', 'Monaragala'),
    ('NISHSHANKA M.M.V.', 'BADALKUMBURA', 'Uva', 'Monaragala', 'Monaragala'),
    ('MALWATTAWALA M.M.V.', 'WELLAWAYA.', 'Uva', 'Monaragala', 'Wellawaya'),
    ('DUTUGEMUNU M.M.V.', 'BUTTALA.', 'Uva', 'Monaragala', 'Wellawaya'),
    ('KATHARAGAMA PRESIDENTS CENTER COLLEGE', 'KATHARAGAMA', 'Uva', 'Monaragala', 'Wellawaya'),
    ('THANAMALWILA M.M.V', 'THANAMALWILA NATIONL SCHOOL,THANAMALWILA', 'Uva', 'Monaragala', 'Wellawaya'),
    ('SIYAMBALANDUWA M.V.', 'SIYAMBALANDUWA.', 'Uva', 'Monaragala', 'Monaragala'),
    ('EHELIYAGODA M.M.V.', 'EHELIYAGODA', 'Sabaragamuwa', 'Ratnapura', 'Ratnapura'),
    ('FERGUSON HIGH SCHOOL', 'RATNAPURA', 'Sabaragamuwa', 'Ratnapura', 'Ratnapura'),
    ('SUMANA BALIKA VIDYALAYA', 'RATHNAPURA', 'Sabaragamuwa', 'Ratnapura', 'Ratnapura'),
    ('ST.ALOYSIUS NATIONAL SCHOOL', 'CHURCH ROAD,RATNAPURA', 'Sabaragamuwa', 'Ratnapura', 'Ratnapura'),
    ('CONVENT OF THE CHILD JESUS NATIONAL SCHOOL', 'RATHNAPURA', 'Sabaragamuwa', 'Ratnapura', 'Ratnapura'),
    ('SIVALI CENTRAL COLLEGE', 'HIDELLANA, RATHNAPURA', 'Sabaragamuwa', 'Ratnapura', 'Ratnapura'),
    ('GANKANDA CENTRAL COLLEGE', 'PELMADULLA', 'Sabaragamuwa', 'Ratnapura', 'Ratnapura'),
    ('ST. JHONE TAMIL M.V.', 'RAKWANA', 'Sabaragamuwa', 'Ratnapura', 'Embilipitiya'),
    ('BALANGODA ANANDA MAITHREYA M.M.V.', 'BALANGODA', 'Sabaragamuwa', 'Ratnapura', 'Balangoda'),
    ('RAHULA NATIONAL SCHOOL', 'GODAKAWELA', 'Sabaragamuwa', 'Ratnapura', 'Embilipitiya'),
    ('KARAWITA M.M.V.', 'UDA KARAWITA KARAWITA', 'Sabaragamuwa', 'Ratnapura', 'Nivitigala'),
    ('KALAWANA NATIONAL SCHOOL', 'KALAWANA', 'Sabaragamuwa', 'Ratnapura', 'Nivitigala'),
    ('KOLONNA NATIONAL SCHOOL', 'KOLONNA', 'Sabaragamuwa', 'Ratnapura', 'Embilipitiya'),
    ('PRESIDENT''S COLLEGE', 'NEWTOWN EMBILIPITIYA', 'Sabaragamuwa', 'Ratnapura', 'Embilipitiya'),
    ('JEILANI MUS.M.V.', 'DEHIGASTALAWA, BALANGODA', 'Sabaragamuwa', 'Ratnapura', 'Balangoda'),
    ('KURUVITA M.M.V.', 'KURUVITA', 'Sabaragamuwa', 'Ratnapura', 'Ratnapura'),
    ('DR N M PERERA M.M.V.', 'YATIYANTOTA', 'Sabaragamuwa', 'Kegalle', 'Dehiowita'),
    ('DEHIOWITA NATIONAL SCHOOL', 'DEHIOWITA', 'Sabaragamuwa', 'Kegalle', 'Dehiowita'),
    ('SIRISAMAN NATIONAL SCHOOL', 'VIDYALAMAWATHA DERANIYAGALA', 'Sabaragamuwa', 'Kegalle', 'Dehiowita'),
    ('PINDENIYA M.M.V', 'PINDENIYA,ATALA', 'Sabaragamuwa', 'Kegalle', 'Kegalle'),
    ('RAJASINGHE M.M.V.', 'RUWANWELLA', 'Sabaragamuwa', 'Kegalle', 'Dehiowita'),
    ('PINNAWALA M.M.V.', 'RAMBUKKANA', 'Sabaragamuwa', 'Kegalle', 'Mawanella'),
    ('ZAHIRA COLLEGE', 'MAWANELLA', 'Sabaragamuwa', 'Kegalle', 'Mawanella'),
    ('MAYURAPADA M.V', 'MAWANELLA', 'Sabaragamuwa', 'Kegalle', 'Mawanella'),
    ('MAWATHAGODA RIVISANDA M.M.V.', 'USSAPITIYA', 'Sabaragamuwa', 'Kegalle', 'Mawanella'),
    ('KEGALU BALIKA M.V', 'KEGALLE', 'Sabaragamuwa', 'Kegalle', 'Kegalle'),
    ('KEGALU M.V', 'KEGALLE', 'Sabaragamuwa', 'Kegalle', 'Kegalle'),
    ('ST.MARY''S M.V', 'KEGALLE', 'Sabaragamuwa', 'Kegalle', 'Kegalle'),
    ('ST JOSEPH''S BALIKA M.V', 'KEGALLE', 'Sabaragamuwa', 'Kegalle', 'Kegalle'),
    ('SWARNAJAYANTHI NATIONAL SCHOOL', 'KUMARATHUNGA MUNIDASA ROAD,KEGALLE', 'Sabaragamuwa', 'Kegalle', 'Kegalle'),
    ('DUDLEY SENANAYAKA M.M.V', 'THOLANGAMUWA', 'Sabaragamuwa', 'Kegalle', 'Kegalle');